FROM ghcr.io/m-mizutani/octovy:769d0a250f2ac603d99d4ee2c1186bff3d78c1d8

WORKDIR /

ENV OCTOVY_LOG_LEVEL=info
ENV OCTOVY_LOG_FORMAT=json
ENV OCTOVY_GITHUB_APP_ID=891574
ENV OCTOVY_BIGQUERY_PROJECT_ID=mztn-octovy
ENV OCTOVY_BIGQUERY_DATASET_ID=octovy
ENV OCTOVY_ADDR=0.0.0.0:8080
ENV OCTOVY_FIRESTORE_PROJECT_ID=mztn-octovy
ENV OCTOVY_FIRESTORE_DATABASE_ID=octovy

ENTRYPOINT ["/octovy"]
