name: deploy

on:
  push:
    branches:
      - main

env:
  TAG_NAME: octovy-deploy:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/76857761541/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: octovy-deployer@mztn-octovy.iam.gserviceaccount.com
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to Google Artifact Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/mztn-octovy/service-images/octovy:${{ github.sha }}
      - name: Deploy to Cloud Run Job
        run: |
          gcloud beta run deploy octovy \
            --image=asia-northeast1-docker.pkg.dev/mztn-octovy/service-images/octovy:${{ github.sha }} \
            --region=asia-northeast1 \
            --ingress=all \
            --set-env-vars "
              OCTOVY_GITHUB_APP_PRIVATE_KEY=${{ secrets.OCTOVY_GITHUB_APP_PRIVATE_KEY }},
              OCTOVY_GITHUB_APP_SECRET=${{ secrets.OCTOVY_GITHUB_APP_SECRET }}" \
            --args run \
            --service-account=octovy-runner@mztn-octovy.iam.gserviceaccount.com
